# Generated by Django 2.1.5 on 2019-08-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroroles',
            options={'verbose_name_plural': 'HeroRoles'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='heroroles',
            name='role',
            field=models.CharField(choices=[('Carry', 'Carry'), ('Support', 'Support'), ('Pusher', 'Pusher'), ('Jungler', 'Jungler'), ('Disabler', 'Disabler'), ('Initiator', 'Initiator'), ('Escape', 'Escape'), ('Durable', 'Durable'), ('Nuker', 'Nuker')], max_length=50, unique=True),
        ),
    ]
