# Generated by Django 2.1.5 on 2019-08-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0002_auto_20190830_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityBehaviors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.CharField(choices=[('Passive', 'Passive'), ('No Target', 'No Target'), ('Point Target', 'Point Target'), ('Unit Target', 'Unit Target'), ('AOE', 'AOE'), ('Channeled', 'Channeled'), ('Instant Cast', 'Instant Cast'), ('Autocast', 'Autocast')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'AbilityBehaviors',
            },
        ),
        migrations.CreateModel(
            name='HeroAbilityBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilityName', models.CharField(max_length=100, unique=True)),
                ('dname', models.CharField(max_length=100)),
                ('dmg_type', models.CharField(choices=[('Pure', 'Pure'), ('Magical', 'Magical'), ('Physical', 'Physical')], max_length=50)),
                ('bkbPierce', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=250)),
                ('opendota_img', models.CharField(max_length=100)),
                ('manaCost', models.IntegerField(null=True)),
                ('cooldown', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota_chat.Hero')),
                ('matchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota_chat.Match')),
                ('valveID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota_chat.SteamUser')),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='HeroAbility',
            fields=[
                ('heroabilitybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dota_chat.HeroAbilityBaseModel')),
                ('isChannelCancelling', models.BooleanField(default=False)),
                ('isHardDisable', models.BooleanField(default=False)),
                ('isDisable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'HeroAbilities',
            },
            bases=('dota_chat.heroabilitybasemodel',),
        ),
        migrations.AddField(
            model_name='heroabilitybasemodel',
            name='behavior',
            field=models.ManyToManyField(to='dota_chat.AbilityBehaviors'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('valveID', 'hero', 'matchID')},
        ),
        migrations.AddField(
            model_name='hero',
            name='abilities',
            field=models.ManyToManyField(to='dota_chat.HeroAbility'),
        ),
    ]
