# Generated by Django 2.1.5 on 2019-08-30 17:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0003_auto_20190830_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroabilitybasemodel',
            name='cooldown'
        ),
        migrations.AddField(
            model_name='heroabilitybasemodel',
            name='cooldown',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),


        migrations.RemoveField(
            model_name='heroabilitybasemodel',
            name='manaCost'
        ),
        migrations.AddField(
            model_name='heroabilitybasemodel',
            name='manaCost',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
