# Generated by Django 2.1.5 on 2019-08-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0004_auto_20190830_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='dmg_type',
            field=models.CharField(choices=[('Pure', 'Pure'), ('Magical', 'Magical'), ('Physical', 'Physical')], max_length=50, null=True),
        ),
    ]
