# Generated by Django 2.1.5 on 2019-08-30 17:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0005_auto_20190830_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='cooldown',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='manaCost',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None),
        ),
    ]
