# Generated by Django 2.1.5 on 2019-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0006_auto_20190830_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='description',
            field=models.TextField(),
        ),
    ]
