# Generated by Django 2.1.5 on 2019-08-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0007_auto_20190830_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitybehaviors',
            name='behavior',
            field=models.CharField(choices=[('Passive', 'Passive'), ('No Target', 'No Target'), ('Point Target', 'Point Target'), ('Unit Target', 'Unit Target'), ('AOE', 'AOE'), ('Channeled', 'Channeled'), ('Instant Cast', 'Instant Cast'), ('Autocast', 'Autocast'), ('Hidden', 'Hidden'), ('Attack Modifier', 'Attack Modifier')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
