# Generated by Django 2.1.5 on 2019-08-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0008_auto_20190830_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='opendota_img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
