# Generated by Django 2.1.5 on 2019-08-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0010_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dname',
            field=models.CharField(max_length=100),
        ),
    ]
