# Generated by Django 2.1.5 on 2019-08-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0011_auto_20190830_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemName',
            field=models.CharField(default='default', max_length=100, unique=False),
            preserve_default=False,
        ),
    ]
