# Generated by Django 2.1.5 on 2019-08-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0012_item_itemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
