# Generated by Django 2.1.5 on 2019-08-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0013_auto_20190830_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroability',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
