# Generated by Django 2.1.5 on 2019-09-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0014_auto_20190830_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='dmg_type',
            field=models.CharField(blank=True, choices=[('Pure', 'Pure'), ('Magical', 'Magical'), ('Physical', 'Physical'), (None, 'null')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='opendota_img',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='lore',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='opendota_img',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
