# Generated by Django 2.1.5 on 2019-09-01 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0015_auto_20190901_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('chatText', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'ChatEntries',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('RADIANT', 'Radiant'), ('DIRE', 'Dire')], default='RADIANT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatentry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota_chat.Player'),
        ),
    ]
