# Generated by Django 2.1.5 on 2019-09-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0016_auto_20190901_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatentry',
            old_name='time',
            new_name='chatTime',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('valveID', 'name', 'hero', 'matchID')},
        ),
    ]
