# Generated by Django 2.1.5 on 2019-09-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0018_auto_20190903_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wonMatch',
            field=models.BooleanField(default=False),
        ),
    ]
