# Generated by Django 2.1.5 on 2019-09-05 05:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0021_heroability_abilityslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroability',
            name='abilitySlot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='cooldown',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='heroabilitybasemodel',
            name='manaCost',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), blank=True, null=True, size=None),
        ),
    ]
