# Generated by Django 2.1.5 on 2019-09-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0022_auto_20190905_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hero',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='heroability',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='herobasemodel',
            name='opendota_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='herobasemodel',
            name='opendota_img',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='cooldown',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='manaCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steamuser',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
