# Generated by Django 2.1.5 on 2019-09-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0024_player_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='human_players',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='match_seq_num',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
