# Generated by Django 2.1.5 on 2019-09-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0026_match_radiant_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroability',
            name='isChanneled',
            field=models.BooleanField(default=False),
        ),
    ]
