# Generated by Django 2.1.5 on 2019-09-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0027_heroability_ischanneled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityBehaviorColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='abilitybehaviors',
            name='behavior',
            field=models.CharField(choices=[('Passive', 'Passive'), ('No Target', 'No Target'), ('Point Target', 'Point Target'), ('Unit Target', 'Unit Target'), ('AOE', 'AOE'), ('Channeled', 'Channeled'), ('Instant Cast', 'Instant Cast'), ('Autocast', 'Autocast'), ('Hidden', 'Hidden'), ('Attack Modifier', 'Attack Modifier'), ('Channel Cancelling', 'Channel Cancelling'), ('Hard Disable', 'Hard Disable'), ('Channeled', 'Channeled'), ('Channeled Cast', 'Channeled Cast'), ('Core Spell', 'Core Spell'), ('Grants Self Physical Immunity', 'Grants Self Physical Immunity'), ('Grants Self Magic Immunity', 'Grants Self Magic Immunity'), ('Grants Ally Physical Immunity', 'Grants Ally Physical Immunity'), ('Grants Ally Magic Immunity', 'Grants Ally Magic Immunity'), ('Grants Enemy Physical Immunity', 'Grants Enemy Physical Immunity'), ('Grants Enemy Magic Immunity', 'Grants Enemy Magic Immunity'), ('Bash', 'Bash'), ('Root', 'Root'), ('Disarms Enemy', 'Disarms Enemy'), ('Disarms Ally', 'Disarms Ally'), ('Basic Dispel Self', 'Basic Dispel Self'), ('Basic Dispel Ally', 'Basic Dispel Ally'), ('Basic Dispel Enemy', 'Basic Dispel Enemy'), ('Strong Dispel Self', 'Strong Dispel Self'), ('Strong Dispel Ally', 'Strong Dispel Ally'), ('Strong Dispel Enemy', 'Strong Dispel Enemy'), ('Grants Invisibility', 'Grants Invisibility'), ('Grants True Sight', 'Grants True Sight'), ('Enhanced By Scepter', 'Enhanced By Scepter'), ('Granted By Scepter', 'Granted By Scepter'), ('Heals Teammates', 'Heals Teammates'), ('AOE Denial', 'AOE Denial'), ('Skill Shot', 'Skill Shot'), ('Repositions Enemies', 'Repositions Enemies'), ('Repositions Allies', 'Repositions Allies'), ('Mutes', 'Mutes')], max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='abilitybehaviors',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dota_chat.AbilityBehaviorColors'),
        ),
    ]
