# Generated by Django 2.1.5 on 2019-09-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0028_auto_20190917_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abilitybehaviorcolors',
            old_name='color',
            new_name='colorDescriptiveName',
        ),
        migrations.AddField(
            model_name='abilitybehaviorcolors',
            name='colorHex',
            field=models.CharField(default='#FFFFFF', max_length=10),
            preserve_default=False,
        ),
    ]
