# Generated by Django 2.1.5 on 2019-09-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0030_auto_20190917_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitybehaviorcolors',
            name='colorDescriptiveName',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
