# Generated by Django 2.1.5 on 2019-09-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0032_auto_20190918_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bans',
            field=models.ManyToManyField(to='dota_chat.Hero'),
        ),
    ]
