# Generated by Django 2.1.5 on 2019-09-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0033_match_bans'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_mode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='patch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='region',
            field=models.IntegerField(null=True),
        ),
    ]
