# Generated by Django 2.1.5 on 2019-09-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0034_auto_20190918_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
    ]
