# Generated by Django 2.1.5 on 2019-09-23 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0035_match_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHeroStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('with_games', models.IntegerField(default=0)),
                ('with_win', models.IntegerField(default=0)),
                ('against_games', models.IntegerField(default=0)),
                ('against_win', models.IntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota_chat.Hero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota_chat.SteamUser')),
            ],
            options={
                'verbose_name_plural': 'UserHeroStats',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userherostats',
            unique_together={('user', 'hero')},
        ),
    ]
