# Generated by Django 2.1.5 on 2019-09-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota_chat', '0036_auto_20190923_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobasemodel',
            name='chatSentiment',
            field=models.FloatField(default=0.0),
        ),
    ]
